import Head from 'next/head'
import BaseLayout from "../src/ui/layout/base-layout";
import Button from '@mui/material/Button';
import ArticleCard from "../src/components/cards/articleCard";
import {useState} from "react";
import {observer} from "mobx-react";
import HomeController from "../src/data/controller/homeController/homeController";
const controller = new HomeController()
 const Home = (observer((props) => {
     const [showMore , setShowMore] = useState(false)

  return (
    <div className={'container'}>
      <Head>
        <title>sos Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'container mx-auto'}>
          <div className={'flex justify-between items-center mt-6 mb-3 flex-row-reverse'}>
              <h1 className={'text-xl font-semibold'}> مقاله ها</h1>
              {
                  !showMore && <Button onClick={()=>setShowMore(true)} className={'font-semibold'}> <span className={'button-style-font'}>نمایش همه</span></Button>
              }

          </div>
           <div className={'flex md:flex-row flex-col flex-row-reverse flex-wrap justify-center md:justify-end'}>
               {
                   controller.List.map((item , index) => {
                       if(index<4 || showMore) {
                           return <ArticleCard item={item} key={item.title + index}/>
                       }
                   })
               }
           </div>
      </div>
    </div>
  )
}))
Home.Layout = BaseLayout
// export const getStaticProps = async ({ locale }) => {
//     // if (process.env.NODE_ENV === 'development') {
//     //     await
//     // }
//
//     // return {
//     //     props: {
//     //         ...(await serverSideTranslations(locale, ['common'])),
//     //     },
//     // }
// }
export default Home