import Head from 'next/head'
import BaseLayout from "../src/ui/layout/base-layout";
import Button from '@mui/material/Button';
 function Home() {
  return (
    <div className={'container'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div><Button variant="contained">Hello World</Button></div>
    </div>
  )
}
Home.Layout = BaseLayout
// export const getStaticProps = async ({ locale }) => {
//     // if (process.env.NODE_ENV === 'development') {
//     //     await
//     // }
//
//     // return {
//     //     props: {
//     //         ...(await serverSideTranslations(locale, ['common'])),
//     //     },
//     // }
// }
export default Home